name: ftp-deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build --clean

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://ftp.cluster023.hosting.ovh.net/
          username: guillaumpm
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./site/
          server-dir: ./rendering-techniques/